//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eggplant
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDBerenjenaContainer : DbContext
    {
        public BDBerenjenaContainer()
            : base("name=BDBerenjenaContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Tokens> TokensSet { get; set; }
        public DbSet<Solicitud> SolicitudSet { get; set; }
        public DbSet<LineaSolicitud> LineaSolicitudSet { get; set; }
    }
}
