//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eggplant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        public Pedido()
        {
            this.LineaPedido = new HashSet<LineaPedido>();
        }
    
        public int Id { get; set; }
        public int oferta_id { get; set; }
        public System.DateTime timeStamp { get; set; }
        public string status { get; set; }
    
        public virtual ICollection<LineaPedido> LineaPedido { get; set; }
        public virtual Solicitud Solicitud { get; set; }
    }
}
