//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eggplant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitud
    {
        public Solicitud()
        {
            this.LineaSolicitud = new HashSet<LineaSolicitud>();
            this.Pedidos = new HashSet<Pedido>();
        }
    
        public int Id { get; set; }
        public int sg_id { get; set; }
        public System.DateTime timeStamp { get; set; }
        public string status { get; set; }
        public string user_id { get; set; }
    
        public virtual ICollection<LineaSolicitud> LineaSolicitud { get; set; }
        public virtual ICollection<Pedido> Pedidos { get; set; }
    }
}
