//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Berenjena
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tokens
    {
        public int token { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public string state { get; set; }
    }
}
