//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerSystem
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class Desguace
    {
        public Desguace()
        {
            this.Ofertas = new HashSet<Oferta>();
        }
    
        public int id { get; set; }
        public bool active { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<Oferta> Ofertas { get; set; }
    }
}
