//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerSystem
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class LineaOfertaSeleccionada
    {
        public LineaOfertaSeleccionada()
        {
            this.LineasOferta = new HashSet<LineaOferta>();
        }
    
        public int Id { get; set; }
        public string quantity { get; set; }
        public int LineaSolicitud_id { get; set; }
    
        public virtual LineaSolicitud LineaSolicitud { get; set; }
        public virtual ICollection<LineaOferta> LineasOferta { get; set; }
    }
}
