//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerSystem
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class LineaPedidoOferta
    {
        public int id { get; set; }
        public int id_en_desguace { get; set; }
        public int price { get; set; }
        public int quantity { get; set; }
        public int Oferta_id { get; set; }
    
        public virtual Oferta Oferta { get; set; }
    }
}
