//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerSystem
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class LineaSolicitud
    {
        public LineaSolicitud()
        {
            this.LineasOferta = new HashSet<LineaOferta>();
        }
    
        public int Id { get; set; }
        public int quantity { get; set; }
        public int id_en_taller { get; set; }
        public string description { get; set; }
        public int SolicitudId { get; set; }
        public string status { get; set; }
        public string flag { get; set; }
    
        public virtual Solicitud Solicitud { get; set; }
        public virtual ICollection<LineaOferta> LineasOferta { get; set; }
    }
}
