//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerSystem
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class LineaOferta
    {
        public int Id { get; set; }
        public int id_en_desguace { get; set; }
        public double price { get; set; }
        public int quantity { get; set; }
        public int OfertaId { get; set; }
        public string notes { get; set; }
        public int LineaSolicitudId { get; set; }
        public string status { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual Oferta Oferta { get; set; }
        public virtual LineaSolicitud LineaSolicitud { get; set; }
        public virtual LineaOfertaSeleccionada LineaOfertaSeleccionada { get; set; }
    }
}
