//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerSystem
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class LineaOfertaSeleccionada
    {
        public LineaOfertaSeleccionada()
        {
            this.LineasOferta = new HashSet<LineaOferta>();
        }
    
        public int Id { get; set; }
        public string quantity { get; set; }
        public int LineaSolicitud_id { get; set; }
    
        public virtual LineaSolicitud LineaSolicitud { get; set; }
        public virtual ICollection<LineaOferta> LineasOferta { get; set; }
    }
}
