//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerSystem
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class LineaPedidoOferta
    {
        public int id { get; set; }
        public int id_en_desguace { get; set; }
        public int price { get; set; }
        public int quantity { get; set; }
        public int Oferta_id { get; set; }
    
        public virtual Oferta Oferta { get; set; }
    }
}
