//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerSystem
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class LineaSolicitud
    {
        public LineaSolicitud()
        {
            this.LineasOfertaSeleccionada = new HashSet<LineaOfertaSeleccionada>();
        }
    
        public int id { get; set; }
        public int price { get; set; }
        public int quantity { get; set; }
        public string id_en_taller { get; set; }
        public int Solicitud_id { get; set; }
    
        public virtual Solicitud Solicitud { get; set; }
        public virtual ICollection<LineaOfertaSeleccionada> LineasOfertaSeleccionada { get; set; }
    }
}
