//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class managersystemEntities : DbContext
    {
        public managersystemEntities()
            : base("name=managersystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Desguace> DesguaceConjunto { get; set; }
        public DbSet<Oferta> OfertaConjunto { get; set; }
        public DbSet<LineaOferta> LineaPedidoOfertaConjunto { get; set; }
        public DbSet<Taller> Tallers { get; set; }
        public DbSet<Solicitud> Solicituds { get; set; }
        public DbSet<LineaSolicitud> LineaSolicituds { get; set; }
        public DbSet<LineaOfertaSeleccionada> LineasOfertaSeleccionada { get; set; }
    }
}
