//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class managersystemEntities : DbContext
    {
        public managersystemEntities()
            : base("name=managersystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Desguace> DesguaceSet { get; set; }
        public DbSet<Oferta> OfertaSet { get; set; }
        public DbSet<LineaOferta> LineaOfertaSet { get; set; }
        public DbSet<Taller> TallerSet { get; set; }
        public DbSet<Solicitud> SolicitudSet { get; set; }
        public DbSet<LineaSolicitud> LineasSolicitudSet { get; set; }
        public DbSet<LineaOfertaSeleccionada> LineaOfertaSeleccionadaSet { get; set; }
        public DbSet<Token> TokenSet { get; set; }
    }
}
