//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerSystem
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class Oferta
    {
        public Oferta()
        {
            this.LineaPedidoOferta = new HashSet<LineaPedidoOferta>();
        }
    
        public int id { get; set; }
        public int Desguace_id { get; set; }
        public int id_en_desguace { get; set; }
        public System.DateTime date { get; set; }
        public string state { get; set; }
        public Nullable<int> Desguace_id1 { get; set; }
        public int TallerId { get; set; }
        public Nullable<int> TallerId1 { get; set; }
    
        public virtual ICollection<LineaPedidoOferta> LineaPedidoOferta { get; set; }
        public virtual Desguace Desguace { get; set; }
        public virtual Taller Taller { get; set; }
    }
}
