//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerSystem
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class Solicitud
    {
        public Solicitud()
        {
            this.deleted = false;
            this.LineasSolicitud = new HashSet<LineaSolicitud>();
            this.Ofertas = new HashSet<Oferta>();
        }
    
        public int Id { get; set; }
        public int id_en_taller { get; set; }
        public System.DateTime date { get; set; }
        public string state { get; set; }
        public int TallerId { get; set; }
        public bool deleted { get; set; }
        public System.DateTime deadline { get; set; }
    
        public virtual Taller Taller { get; set; }
        public virtual ICollection<LineaSolicitud> LineasSolicitud { get; set; }
        public virtual ICollection<Oferta> Ofertas { get; set; }
    }
}
