//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerSystem
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class Solicitud
    {
        public Solicitud()
        {
            this.Ofertas = new HashSet<Oferta>();
            this.LineasSolicitud = new HashSet<LineaSolicitud>();
        }
    
        public int id { get; set; }
        public int id_en_taller { get; set; }
        public System.DateTime date { get; set; }
        public string state { get; set; }
        public int TallerId { get; set; }
    
        public virtual Taller Taller { get; set; }
        public virtual ICollection<Oferta> Ofertas { get; set; }
        public virtual ICollection<LineaSolicitud> LineasSolicitud { get; set; }
    }
}
