//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerSystem
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class Taller
    {
        public Taller()
        {
            this.deleted = false;
            this.Solicitudes = new HashSet<Solicitud>();
            this.Tokens = new HashSet<Token>();
        }
    
        public int Id { get; set; }
        public bool active { get; set; }
        public string name { get; set; }
        public bool deleted { get; set; }
    
        public virtual ICollection<Solicitud> Solicitudes { get; set; }
        public virtual ICollection<Token> Tokens { get; set; }
    }
}
