//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerSystem
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class Taller
    {
        public Taller()
        {
            this.Ofertas = new HashSet<Oferta>();
        }
    
        public int Id { get; set; }
        public bool active { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<Oferta> Ofertas { get; set; }
    }
}
