//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerSystem
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class Token
    {
        public int Id { get; set; }
        public System.DateTime created { get; set; }
        public System.DateTime updated { get; set; }
        public string token { get; set; }
        public bool is_valid { get; set; }
        public Nullable<int> DesguaceId { get; set; }
        public Nullable<int> TallerId { get; set; }
    
        public virtual Desguace Desguace { get; set; }
        public virtual Taller Taller { get; set; }
    }
}
