//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Berenjena.ServiceTaller {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Taller", Namespace="http://schemas.datacontract.org/2004/07/ManagerSystem")]
    [System.SerializableAttribute()]
    public partial class Taller : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Berenjena.ServiceTaller.Solicitud[] SolicitudesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool activeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Berenjena.ServiceTaller.Solicitud[] Solicitudes {
            get {
                return this.SolicitudesField;
            }
            set {
                if ((object.ReferenceEquals(this.SolicitudesField, value) != true)) {
                    this.SolicitudesField = value;
                    this.RaisePropertyChanged("Solicitudes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool active {
            get {
                return this.activeField;
            }
            set {
                if ((this.activeField.Equals(value) != true)) {
                    this.activeField = value;
                    this.RaisePropertyChanged("active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Solicitud", Namespace="http://schemas.datacontract.org/2004/07/ManagerSystem")]
    [System.SerializableAttribute()]
    public partial class Solicitud : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Berenjena.ServiceTaller.LineaSolicitud[] LineasSolicitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Berenjena.ServiceTaller.Oferta[] OfertasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Berenjena.ServiceTaller.Taller TallerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TallerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_en_tallerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string stateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Berenjena.ServiceTaller.LineaSolicitud[] LineasSolicitud {
            get {
                return this.LineasSolicitudField;
            }
            set {
                if ((object.ReferenceEquals(this.LineasSolicitudField, value) != true)) {
                    this.LineasSolicitudField = value;
                    this.RaisePropertyChanged("LineasSolicitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Berenjena.ServiceTaller.Oferta[] Ofertas {
            get {
                return this.OfertasField;
            }
            set {
                if ((object.ReferenceEquals(this.OfertasField, value) != true)) {
                    this.OfertasField = value;
                    this.RaisePropertyChanged("Ofertas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Berenjena.ServiceTaller.Taller Taller {
            get {
                return this.TallerField;
            }
            set {
                if ((object.ReferenceEquals(this.TallerField, value) != true)) {
                    this.TallerField = value;
                    this.RaisePropertyChanged("Taller");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TallerId {
            get {
                return this.TallerIdField;
            }
            set {
                if ((this.TallerIdField.Equals(value) != true)) {
                    this.TallerIdField = value;
                    this.RaisePropertyChanged("TallerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime date {
            get {
                return this.dateField;
            }
            set {
                if ((this.dateField.Equals(value) != true)) {
                    this.dateField = value;
                    this.RaisePropertyChanged("date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_en_taller {
            get {
                return this.id_en_tallerField;
            }
            set {
                if ((this.id_en_tallerField.Equals(value) != true)) {
                    this.id_en_tallerField = value;
                    this.RaisePropertyChanged("id_en_taller");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string state {
            get {
                return this.stateField;
            }
            set {
                if ((object.ReferenceEquals(this.stateField, value) != true)) {
                    this.stateField = value;
                    this.RaisePropertyChanged("state");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LineaSolicitud", Namespace="http://schemas.datacontract.org/2004/07/ManagerSystem")]
    [System.SerializableAttribute()]
    public partial class LineaSolicitud : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Berenjena.ServiceTaller.LineaOfertaSeleccionada[] LineasOfertaSeleccionadaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Berenjena.ServiceTaller.Solicitud SolicitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Solicitud_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_en_tallerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int quantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Berenjena.ServiceTaller.LineaOfertaSeleccionada[] LineasOfertaSeleccionada {
            get {
                return this.LineasOfertaSeleccionadaField;
            }
            set {
                if ((object.ReferenceEquals(this.LineasOfertaSeleccionadaField, value) != true)) {
                    this.LineasOfertaSeleccionadaField = value;
                    this.RaisePropertyChanged("LineasOfertaSeleccionada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Berenjena.ServiceTaller.Solicitud Solicitud {
            get {
                return this.SolicitudField;
            }
            set {
                if ((object.ReferenceEquals(this.SolicitudField, value) != true)) {
                    this.SolicitudField = value;
                    this.RaisePropertyChanged("Solicitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Solicitud_id {
            get {
                return this.Solicitud_idField;
            }
            set {
                if ((this.Solicitud_idField.Equals(value) != true)) {
                    this.Solicitud_idField = value;
                    this.RaisePropertyChanged("Solicitud_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_en_taller {
            get {
                return this.id_en_tallerField;
            }
            set {
                if ((this.id_en_tallerField.Equals(value) != true)) {
                    this.id_en_tallerField = value;
                    this.RaisePropertyChanged("id_en_taller");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int quantity {
            get {
                return this.quantityField;
            }
            set {
                if ((this.quantityField.Equals(value) != true)) {
                    this.quantityField = value;
                    this.RaisePropertyChanged("quantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Oferta", Namespace="http://schemas.datacontract.org/2004/07/ManagerSystem")]
    [System.SerializableAttribute()]
    public partial class Oferta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Berenjena.ServiceTaller.Desguace DesguaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Desguace_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Berenjena.ServiceTaller.LineaOferta[] LineasOfertaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Berenjena.ServiceTaller.Solicitud SolicitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Solicitud_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_en_desguaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string stateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Berenjena.ServiceTaller.Desguace Desguace {
            get {
                return this.DesguaceField;
            }
            set {
                if ((object.ReferenceEquals(this.DesguaceField, value) != true)) {
                    this.DesguaceField = value;
                    this.RaisePropertyChanged("Desguace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Desguace_id {
            get {
                return this.Desguace_idField;
            }
            set {
                if ((this.Desguace_idField.Equals(value) != true)) {
                    this.Desguace_idField = value;
                    this.RaisePropertyChanged("Desguace_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Berenjena.ServiceTaller.LineaOferta[] LineasOferta {
            get {
                return this.LineasOfertaField;
            }
            set {
                if ((object.ReferenceEquals(this.LineasOfertaField, value) != true)) {
                    this.LineasOfertaField = value;
                    this.RaisePropertyChanged("LineasOferta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Berenjena.ServiceTaller.Solicitud Solicitud {
            get {
                return this.SolicitudField;
            }
            set {
                if ((object.ReferenceEquals(this.SolicitudField, value) != true)) {
                    this.SolicitudField = value;
                    this.RaisePropertyChanged("Solicitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Solicitud_id {
            get {
                return this.Solicitud_idField;
            }
            set {
                if ((this.Solicitud_idField.Equals(value) != true)) {
                    this.Solicitud_idField = value;
                    this.RaisePropertyChanged("Solicitud_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime date {
            get {
                return this.dateField;
            }
            set {
                if ((this.dateField.Equals(value) != true)) {
                    this.dateField = value;
                    this.RaisePropertyChanged("date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_en_desguace {
            get {
                return this.id_en_desguaceField;
            }
            set {
                if ((this.id_en_desguaceField.Equals(value) != true)) {
                    this.id_en_desguaceField = value;
                    this.RaisePropertyChanged("id_en_desguace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string state {
            get {
                return this.stateField;
            }
            set {
                if ((object.ReferenceEquals(this.stateField, value) != true)) {
                    this.stateField = value;
                    this.RaisePropertyChanged("state");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LineaOfertaSeleccionada", Namespace="http://schemas.datacontract.org/2004/07/ManagerSystem")]
    [System.SerializableAttribute()]
    public partial class LineaOfertaSeleccionada : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Berenjena.ServiceTaller.LineaSolicitud LineaSolicitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LineaSolicitud_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Berenjena.ServiceTaller.LineaOferta[] LineasOfertaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string quantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Berenjena.ServiceTaller.LineaSolicitud LineaSolicitud {
            get {
                return this.LineaSolicitudField;
            }
            set {
                if ((object.ReferenceEquals(this.LineaSolicitudField, value) != true)) {
                    this.LineaSolicitudField = value;
                    this.RaisePropertyChanged("LineaSolicitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LineaSolicitud_id {
            get {
                return this.LineaSolicitud_idField;
            }
            set {
                if ((this.LineaSolicitud_idField.Equals(value) != true)) {
                    this.LineaSolicitud_idField = value;
                    this.RaisePropertyChanged("LineaSolicitud_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Berenjena.ServiceTaller.LineaOferta[] LineasOferta {
            get {
                return this.LineasOfertaField;
            }
            set {
                if ((object.ReferenceEquals(this.LineasOfertaField, value) != true)) {
                    this.LineasOfertaField = value;
                    this.RaisePropertyChanged("LineasOferta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string quantity {
            get {
                return this.quantityField;
            }
            set {
                if ((object.ReferenceEquals(this.quantityField, value) != true)) {
                    this.quantityField = value;
                    this.RaisePropertyChanged("quantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LineaOferta", Namespace="http://schemas.datacontract.org/2004/07/ManagerSystem")]
    [System.SerializableAttribute()]
    public partial class LineaOferta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Berenjena.ServiceTaller.LineaOfertaSeleccionada LineaOfertaSeleccionadaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LineaOfertaSeleccionadaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Berenjena.ServiceTaller.Oferta OfertaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Oferta_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_en_desguaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int quantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Berenjena.ServiceTaller.LineaOfertaSeleccionada LineaOfertaSeleccionada {
            get {
                return this.LineaOfertaSeleccionadaField;
            }
            set {
                if ((object.ReferenceEquals(this.LineaOfertaSeleccionadaField, value) != true)) {
                    this.LineaOfertaSeleccionadaField = value;
                    this.RaisePropertyChanged("LineaOfertaSeleccionada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LineaOfertaSeleccionadaId {
            get {
                return this.LineaOfertaSeleccionadaIdField;
            }
            set {
                if ((this.LineaOfertaSeleccionadaIdField.Equals(value) != true)) {
                    this.LineaOfertaSeleccionadaIdField = value;
                    this.RaisePropertyChanged("LineaOfertaSeleccionadaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Berenjena.ServiceTaller.Oferta Oferta {
            get {
                return this.OfertaField;
            }
            set {
                if ((object.ReferenceEquals(this.OfertaField, value) != true)) {
                    this.OfertaField = value;
                    this.RaisePropertyChanged("Oferta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Oferta_id {
            get {
                return this.Oferta_idField;
            }
            set {
                if ((this.Oferta_idField.Equals(value) != true)) {
                    this.Oferta_idField = value;
                    this.RaisePropertyChanged("Oferta_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_en_desguace {
            get {
                return this.id_en_desguaceField;
            }
            set {
                if ((this.id_en_desguaceField.Equals(value) != true)) {
                    this.id_en_desguaceField = value;
                    this.RaisePropertyChanged("id_en_desguace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int price {
            get {
                return this.priceField;
            }
            set {
                if ((this.priceField.Equals(value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int quantity {
            get {
                return this.quantityField;
            }
            set {
                if ((this.quantityField.Equals(value) != true)) {
                    this.quantityField = value;
                    this.RaisePropertyChanged("quantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Desguace", Namespace="http://schemas.datacontract.org/2004/07/ManagerSystem")]
    [System.SerializableAttribute()]
    public partial class Desguace : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Berenjena.ServiceTaller.Oferta[] OfertasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool activeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Berenjena.ServiceTaller.Oferta[] Ofertas {
            get {
                return this.OfertasField;
            }
            set {
                if ((object.ReferenceEquals(this.OfertasField, value) != true)) {
                    this.OfertasField = value;
                    this.RaisePropertyChanged("Ofertas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool active {
            get {
                return this.activeField;
            }
            set {
                if ((this.activeField.Equals(value) != true)) {
                    this.activeField = value;
                    this.RaisePropertyChanged("active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExposedSolicitud", Namespace="http://schemas.datacontract.org/2004/07/ManagerSystem")]
    [System.SerializableAttribute()]
    public partial class ExposedSolicitud : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Berenjena.ServiceTaller.ExposedLineaSolicitud[] lineasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int taller_idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Berenjena.ServiceTaller.ExposedLineaSolicitud[] lineas {
            get {
                return this.lineasField;
            }
            set {
                if ((object.ReferenceEquals(this.lineasField, value) != true)) {
                    this.lineasField = value;
                    this.RaisePropertyChanged("lineas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int taller_id {
            get {
                return this.taller_idField;
            }
            set {
                if ((this.taller_idField.Equals(value) != true)) {
                    this.taller_idField = value;
                    this.RaisePropertyChanged("taller_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExposedLineaSolicitud", Namespace="http://schemas.datacontract.org/2004/07/ManagerSystem")]
    [System.SerializableAttribute()]
    public partial class ExposedLineaSolicitud : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int quantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int quantity {
            get {
                return this.quantityField;
            }
            set {
                if ((this.quantityField.Equals(value) != true)) {
                    this.quantityField = value;
                    this.RaisePropertyChanged("quantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceTaller.IGestionTaller")]
    public interface IGestionTaller {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionTaller/getTaller", ReplyAction="http://tempuri.org/IGestionTaller/getTallerResponse")]
        Berenjena.ServiceTaller.Taller getTaller(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionTaller/getTaller", ReplyAction="http://tempuri.org/IGestionTaller/getTallerResponse")]
        System.Threading.Tasks.Task<Berenjena.ServiceTaller.Taller> getTallerAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionTaller/addTaller", ReplyAction="http://tempuri.org/IGestionTaller/addTallerResponse")]
        int addTaller(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionTaller/addTaller", ReplyAction="http://tempuri.org/IGestionTaller/addTallerResponse")]
        System.Threading.Tasks.Task<int> addTallerAsync(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionTaller/getState", ReplyAction="http://tempuri.org/IGestionTaller/getStateResponse")]
        int getState(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionTaller/getState", ReplyAction="http://tempuri.org/IGestionTaller/getStateResponse")]
        System.Threading.Tasks.Task<int> getStateAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionTaller/putTaller", ReplyAction="http://tempuri.org/IGestionTaller/putTallerResponse")]
        int putTaller(Berenjena.ServiceTaller.Taller t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionTaller/putTaller", ReplyAction="http://tempuri.org/IGestionTaller/putTallerResponse")]
        System.Threading.Tasks.Task<int> putTallerAsync(Berenjena.ServiceTaller.Taller t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionTaller/deleteTaller", ReplyAction="http://tempuri.org/IGestionTaller/deleteTallerResponse")]
        int deleteTaller(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionTaller/deleteTaller", ReplyAction="http://tempuri.org/IGestionTaller/deleteTallerResponse")]
        System.Threading.Tasks.Task<int> deleteTallerAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionTaller/getSolicitud", ReplyAction="http://tempuri.org/IGestionTaller/getSolicitudResponse")]
        Berenjena.ServiceTaller.ExposedSolicitud getSolicitud(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionTaller/getSolicitud", ReplyAction="http://tempuri.org/IGestionTaller/getSolicitudResponse")]
        System.Threading.Tasks.Task<Berenjena.ServiceTaller.ExposedSolicitud> getSolicitudAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionTaller/addSolicitud", ReplyAction="http://tempuri.org/IGestionTaller/addSolicitudResponse")]
        int addSolicitud(Berenjena.ServiceTaller.ExposedSolicitud s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionTaller/addSolicitud", ReplyAction="http://tempuri.org/IGestionTaller/addSolicitudResponse")]
        System.Threading.Tasks.Task<int> addSolicitudAsync(Berenjena.ServiceTaller.ExposedSolicitud s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionTaller/putSolicitud", ReplyAction="http://tempuri.org/IGestionTaller/putSolicitudResponse")]
        int putSolicitud(Berenjena.ServiceTaller.ExposedSolicitud s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionTaller/putSolicitud", ReplyAction="http://tempuri.org/IGestionTaller/putSolicitudResponse")]
        System.Threading.Tasks.Task<int> putSolicitudAsync(Berenjena.ServiceTaller.ExposedSolicitud s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionTaller/deleteSolicitud", ReplyAction="http://tempuri.org/IGestionTaller/deleteSolicitudResponse")]
        int deleteSolicitud(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionTaller/deleteSolicitud", ReplyAction="http://tempuri.org/IGestionTaller/deleteSolicitudResponse")]
        System.Threading.Tasks.Task<int> deleteSolicitudAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionTaller/getSolicitudes", ReplyAction="http://tempuri.org/IGestionTaller/getSolicitudesResponse")]
        Berenjena.ServiceTaller.ExposedSolicitud[] getSolicitudes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionTaller/getSolicitudes", ReplyAction="http://tempuri.org/IGestionTaller/getSolicitudesResponse")]
        System.Threading.Tasks.Task<Berenjena.ServiceTaller.ExposedSolicitud[]> getSolicitudesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGestionTallerChannel : Berenjena.ServiceTaller.IGestionTaller, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GestionTallerClient : System.ServiceModel.ClientBase<Berenjena.ServiceTaller.IGestionTaller>, Berenjena.ServiceTaller.IGestionTaller {
        
        public GestionTallerClient() {
        }
        
        public GestionTallerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GestionTallerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestionTallerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestionTallerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Berenjena.ServiceTaller.Taller getTaller(int id) {
            return base.Channel.getTaller(id);
        }
        
        public System.Threading.Tasks.Task<Berenjena.ServiceTaller.Taller> getTallerAsync(int id) {
            return base.Channel.getTallerAsync(id);
        }
        
        public int addTaller(string nombre) {
            return base.Channel.addTaller(nombre);
        }
        
        public System.Threading.Tasks.Task<int> addTallerAsync(string nombre) {
            return base.Channel.addTallerAsync(nombre);
        }
        
        public int getState(int id) {
            return base.Channel.getState(id);
        }
        
        public System.Threading.Tasks.Task<int> getStateAsync(int id) {
            return base.Channel.getStateAsync(id);
        }
        
        public int putTaller(Berenjena.ServiceTaller.Taller t) {
            return base.Channel.putTaller(t);
        }
        
        public System.Threading.Tasks.Task<int> putTallerAsync(Berenjena.ServiceTaller.Taller t) {
            return base.Channel.putTallerAsync(t);
        }
        
        public int deleteTaller(int id) {
            return base.Channel.deleteTaller(id);
        }
        
        public System.Threading.Tasks.Task<int> deleteTallerAsync(int id) {
            return base.Channel.deleteTallerAsync(id);
        }
        
        public Berenjena.ServiceTaller.ExposedSolicitud getSolicitud(int id) {
            return base.Channel.getSolicitud(id);
        }
        
        public System.Threading.Tasks.Task<Berenjena.ServiceTaller.ExposedSolicitud> getSolicitudAsync(int id) {
            return base.Channel.getSolicitudAsync(id);
        }
        
        public int addSolicitud(Berenjena.ServiceTaller.ExposedSolicitud s) {
            return base.Channel.addSolicitud(s);
        }
        
        public System.Threading.Tasks.Task<int> addSolicitudAsync(Berenjena.ServiceTaller.ExposedSolicitud s) {
            return base.Channel.addSolicitudAsync(s);
        }
        
        public int putSolicitud(Berenjena.ServiceTaller.ExposedSolicitud s) {
            return base.Channel.putSolicitud(s);
        }
        
        public System.Threading.Tasks.Task<int> putSolicitudAsync(Berenjena.ServiceTaller.ExposedSolicitud s) {
            return base.Channel.putSolicitudAsync(s);
        }
        
        public int deleteSolicitud(int id) {
            return base.Channel.deleteSolicitud(id);
        }
        
        public System.Threading.Tasks.Task<int> deleteSolicitudAsync(int id) {
            return base.Channel.deleteSolicitudAsync(id);
        }
        
        public Berenjena.ServiceTaller.ExposedSolicitud[] getSolicitudes() {
            return base.Channel.getSolicitudes();
        }
        
        public System.Threading.Tasks.Task<Berenjena.ServiceTaller.ExposedSolicitud[]> getSolicitudesAsync() {
            return base.Channel.getSolicitudesAsync();
        }
    }
}
