//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrapWeb.Webservices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExpDesguace", Namespace="http://sorception.azurewebsites.net/")]
    [System.SerializableAttribute()]
    public partial class ExpDesguace : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TokenResponse", Namespace="http://sorception.azurewebsites.net/")]
    [System.SerializableAttribute()]
    public partial class TokenResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ScrapWeb.Webservices.TokenResponseCode statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ScrapWeb.Webservices.TokenResponseCode status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                if ((object.ReferenceEquals(this.tokenField, value) != true)) {
                    this.tokenField = value;
                    this.RaisePropertyChanged("token");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TokenResponse.Code", Namespace="http://schemas.datacontract.org/2004/07/ManagerSystem")]
    public enum TokenResponseCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CREATED = 201,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ACCEPTED = 202,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NON_AUTHORITATIVE = 203,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BAD_REQUEST = 400,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NOT_FOUND = 404,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AMQSolicitudMessage", Namespace="http://sorception.azurewebsites.net/")]
    [System.SerializableAttribute()]
    public partial class AMQSolicitudMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ScrapWeb.Webservices.AMQSolicitudMessageCode codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ScrapWeb.Webservices.ExpSolicitud solicitudField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ScrapWeb.Webservices.AMQSolicitudMessageCode code {
            get {
                return this.codeField;
            }
            set {
                if ((this.codeField.Equals(value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ScrapWeb.Webservices.ExpSolicitud solicitud {
            get {
                return this.solicitudField;
            }
            set {
                if ((object.ReferenceEquals(this.solicitudField, value) != true)) {
                    this.solicitudField = value;
                    this.RaisePropertyChanged("solicitud");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExpSolicitud", Namespace="http://sorception.azurewebsites.net/")]
    [System.SerializableAttribute()]
    public partial class ExpSolicitud : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime deadlineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_en_tallerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ScrapWeb.Webservices.ExpSolicitudLine[] lineasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime deadline {
            get {
                return this.deadlineField;
            }
            set {
                if ((this.deadlineField.Equals(value) != true)) {
                    this.deadlineField = value;
                    this.RaisePropertyChanged("deadline");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_en_taller {
            get {
                return this.id_en_tallerField;
            }
            set {
                if ((this.id_en_tallerField.Equals(value) != true)) {
                    this.id_en_tallerField = value;
                    this.RaisePropertyChanged("id_en_taller");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ScrapWeb.Webservices.ExpSolicitudLine[] lineas {
            get {
                return this.lineasField;
            }
            set {
                if ((object.ReferenceEquals(this.lineasField, value) != true)) {
                    this.lineasField = value;
                    this.RaisePropertyChanged("lineas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string status {
            get {
                return this.statusField;
            }
            set {
                if ((object.ReferenceEquals(this.statusField, value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AMQSolicitudMessage.Code", Namespace="http://schemas.datacontract.org/2004/07/ManagerSystem")]
    public enum AMQSolicitudMessageCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        New = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Update = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Delete = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExpSolicitud.Line", Namespace="http://schemas.datacontract.org/2004/07/ManagerSystem")]
    [System.SerializableAttribute()]
    public partial class ExpSolicitudLine : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string actionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string flagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_en_tallerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int quantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string action {
            get {
                return this.actionField;
            }
            set {
                if ((object.ReferenceEquals(this.actionField, value) != true)) {
                    this.actionField = value;
                    this.RaisePropertyChanged("action");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string flag {
            get {
                return this.flagField;
            }
            set {
                if ((object.ReferenceEquals(this.flagField, value) != true)) {
                    this.flagField = value;
                    this.RaisePropertyChanged("flag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_en_taller {
            get {
                return this.id_en_tallerField;
            }
            set {
                if ((this.id_en_tallerField.Equals(value) != true)) {
                    this.id_en_tallerField = value;
                    this.RaisePropertyChanged("id_en_taller");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int quantity {
            get {
                return this.quantityField;
            }
            set {
                if ((this.quantityField.Equals(value) != true)) {
                    this.quantityField = value;
                    this.RaisePropertyChanged("quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string status {
            get {
                return this.statusField;
            }
            set {
                if ((object.ReferenceEquals(this.statusField, value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AMQOfertaMessage", Namespace="http://sorception.azurewebsites.net/")]
    [System.SerializableAttribute()]
    public partial class AMQOfertaMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ScrapWeb.Webservices.AMQOfertaMessageCode codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string desguace_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ScrapWeb.Webservices.ExpOferta ofertaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ScrapWeb.Webservices.AMQOfertaMessageCode code {
            get {
                return this.codeField;
            }
            set {
                if ((this.codeField.Equals(value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string desguace_id {
            get {
                return this.desguace_idField;
            }
            set {
                if ((object.ReferenceEquals(this.desguace_idField, value) != true)) {
                    this.desguace_idField = value;
                    this.RaisePropertyChanged("desguace_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ScrapWeb.Webservices.ExpOferta oferta {
            get {
                return this.ofertaField;
            }
            set {
                if ((object.ReferenceEquals(this.ofertaField, value) != true)) {
                    this.ofertaField = value;
                    this.RaisePropertyChanged("oferta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExpOferta", Namespace="http://sorception.azurewebsites.net/")]
    [System.SerializableAttribute()]
    public partial class ExpOferta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_en_desguaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ScrapWeb.Webservices.ExpOfertaLine[] lineasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int solicitud_idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_en_desguace {
            get {
                return this.id_en_desguaceField;
            }
            set {
                if ((this.id_en_desguaceField.Equals(value) != true)) {
                    this.id_en_desguaceField = value;
                    this.RaisePropertyChanged("id_en_desguace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ScrapWeb.Webservices.ExpOfertaLine[] lineas {
            get {
                return this.lineasField;
            }
            set {
                if ((object.ReferenceEquals(this.lineasField, value) != true)) {
                    this.lineasField = value;
                    this.RaisePropertyChanged("lineas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int solicitud_id {
            get {
                return this.solicitud_idField;
            }
            set {
                if ((this.solicitud_idField.Equals(value) != true)) {
                    this.solicitud_idField = value;
                    this.RaisePropertyChanged("solicitud_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AMQOfertaMessage.Code", Namespace="http://schemas.datacontract.org/2004/07/ManagerSystem")]
    public enum AMQOfertaMessageCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        New = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Update = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Delete = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExpOferta.Line", Namespace="http://schemas.datacontract.org/2004/07/ManagerSystem")]
    [System.SerializableAttribute()]
    public partial class ExpOfertaLine : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_en_desguaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ScrapWeb.Webservices.ExpOfertaLine.RelatedSolicitud linea_solicitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int linea_solicitud_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string notesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int quantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_en_desguace {
            get {
                return this.id_en_desguaceField;
            }
            set {
                if ((this.id_en_desguaceField.Equals(value) != true)) {
                    this.id_en_desguaceField = value;
                    this.RaisePropertyChanged("id_en_desguace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ScrapWeb.Webservices.ExpOfertaLine.RelatedSolicitud linea_solicitud {
            get {
                return this.linea_solicitudField;
            }
            set {
                if ((object.ReferenceEquals(this.linea_solicitudField, value) != true)) {
                    this.linea_solicitudField = value;
                    this.RaisePropertyChanged("linea_solicitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int linea_solicitud_id {
            get {
                return this.linea_solicitud_idField;
            }
            set {
                if ((this.linea_solicitud_idField.Equals(value) != true)) {
                    this.linea_solicitud_idField = value;
                    this.RaisePropertyChanged("linea_solicitud_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string notes {
            get {
                return this.notesField;
            }
            set {
                if ((object.ReferenceEquals(this.notesField, value) != true)) {
                    this.notesField = value;
                    this.RaisePropertyChanged("notes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double price {
            get {
                return this.priceField;
            }
            set {
                if ((this.priceField.Equals(value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int quantity {
            get {
                return this.quantityField;
            }
            set {
                if ((this.quantityField.Equals(value) != true)) {
                    this.quantityField = value;
                    this.RaisePropertyChanged("quantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="ExpOferta.Line.RelatedSolicitud", Namespace="http://schemas.datacontract.org/2004/07/ManagerSystem")]
        [System.SerializableAttribute()]
        public partial class RelatedSolicitud : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private int linea_solicitud_idField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private int quantityField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public int linea_solicitud_id {
                get {
                    return this.linea_solicitud_idField;
                }
                set {
                    if ((this.linea_solicitud_idField.Equals(value) != true)) {
                        this.linea_solicitud_idField = value;
                        this.RaisePropertyChanged("linea_solicitud_id");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public int quantity {
                get {
                    return this.quantityField;
                }
                set {
                    if ((this.quantityField.Equals(value) != true)) {
                        this.quantityField = value;
                        this.RaisePropertyChanged("quantity");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AMQPedidoMessage", Namespace="http://sorception.azurewebsites.net/")]
    [System.SerializableAttribute()]
    public partial class AMQPedidoMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string desguace_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ScrapWeb.Webservices.ExpPedido pedidoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string desguace_id {
            get {
                return this.desguace_idField;
            }
            set {
                if ((object.ReferenceEquals(this.desguace_idField, value) != true)) {
                    this.desguace_idField = value;
                    this.RaisePropertyChanged("desguace_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ScrapWeb.Webservices.ExpPedido pedido {
            get {
                return this.pedidoField;
            }
            set {
                if ((object.ReferenceEquals(this.pedidoField, value) != true)) {
                    this.pedidoField = value;
                    this.RaisePropertyChanged("pedido");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExpPedido", Namespace="http://sorception.azurewebsites.net/")]
    [System.SerializableAttribute()]
    public partial class ExpPedido : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ScrapWeb.Webservices.ExpPedidoLine[] lineasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int oferta_idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ScrapWeb.Webservices.ExpPedidoLine[] lineas {
            get {
                return this.lineasField;
            }
            set {
                if ((object.ReferenceEquals(this.lineasField, value) != true)) {
                    this.lineasField = value;
                    this.RaisePropertyChanged("lineas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int oferta_id {
            get {
                return this.oferta_idField;
            }
            set {
                if ((this.oferta_idField.Equals(value) != true)) {
                    this.oferta_idField = value;
                    this.RaisePropertyChanged("oferta_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExpPedido.Line", Namespace="http://schemas.datacontract.org/2004/07/ManagerSystem")]
    [System.SerializableAttribute()]
    public partial class ExpPedidoLine : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int linea_oferta_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int quantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int linea_oferta_id {
            get {
                return this.linea_oferta_idField;
            }
            set {
                if ((this.linea_oferta_idField.Equals(value) != true)) {
                    this.linea_oferta_idField = value;
                    this.RaisePropertyChanged("linea_oferta_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int quantity {
            get {
                return this.quantityField;
            }
            set {
                if ((this.quantityField.Equals(value) != true)) {
                    this.quantityField = value;
                    this.RaisePropertyChanged("quantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sorception.azurewebsites.net/", ConfigurationName="Webservices.IGestionDesguace")]
    public interface IGestionDesguace {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sorception.azurewebsites.net/IGestionDesguace/signUp", ReplyAction="http://sorception.azurewebsites.net/IGestionDesguace/signUpResponse")]
        ScrapWeb.Webservices.TokenResponse signUp(ScrapWeb.Webservices.ExpDesguace d);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sorception.azurewebsites.net/IGestionDesguace/signUp", ReplyAction="http://sorception.azurewebsites.net/IGestionDesguace/signUpResponse")]
        System.Threading.Tasks.Task<ScrapWeb.Webservices.TokenResponse> signUpAsync(ScrapWeb.Webservices.ExpDesguace d);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sorception.azurewebsites.net/IGestionDesguace/getState", ReplyAction="http://sorception.azurewebsites.net/IGestionDesguace/getStateResponse")]
        ScrapWeb.Webservices.TokenResponse getState(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sorception.azurewebsites.net/IGestionDesguace/getState", ReplyAction="http://sorception.azurewebsites.net/IGestionDesguace/getStateResponse")]
        System.Threading.Tasks.Task<ScrapWeb.Webservices.TokenResponse> getStateAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sorception.azurewebsites.net/IGestionDesguace/dummy", ReplyAction="http://sorception.azurewebsites.net/IGestionDesguace/dummyResponse")]
        void dummy(ScrapWeb.Webservices.AMQSolicitudMessage s, ScrapWeb.Webservices.AMQOfertaMessage o, ScrapWeb.Webservices.AMQPedidoMessage p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sorception.azurewebsites.net/IGestionDesguace/dummy", ReplyAction="http://sorception.azurewebsites.net/IGestionDesguace/dummyResponse")]
        System.Threading.Tasks.Task dummyAsync(ScrapWeb.Webservices.AMQSolicitudMessage s, ScrapWeb.Webservices.AMQOfertaMessage o, ScrapWeb.Webservices.AMQPedidoMessage p);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGestionDesguaceChannel : ScrapWeb.Webservices.IGestionDesguace, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GestionDesguaceClient : System.ServiceModel.ClientBase<ScrapWeb.Webservices.IGestionDesguace>, ScrapWeb.Webservices.IGestionDesguace {
        
        public GestionDesguaceClient() {
        }
        
        public GestionDesguaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GestionDesguaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestionDesguaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestionDesguaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ScrapWeb.Webservices.TokenResponse signUp(ScrapWeb.Webservices.ExpDesguace d) {
            return base.Channel.signUp(d);
        }
        
        public System.Threading.Tasks.Task<ScrapWeb.Webservices.TokenResponse> signUpAsync(ScrapWeb.Webservices.ExpDesguace d) {
            return base.Channel.signUpAsync(d);
        }
        
        public ScrapWeb.Webservices.TokenResponse getState(string id) {
            return base.Channel.getState(id);
        }
        
        public System.Threading.Tasks.Task<ScrapWeb.Webservices.TokenResponse> getStateAsync(string id) {
            return base.Channel.getStateAsync(id);
        }
        
        public void dummy(ScrapWeb.Webservices.AMQSolicitudMessage s, ScrapWeb.Webservices.AMQOfertaMessage o, ScrapWeb.Webservices.AMQPedidoMessage p) {
            base.Channel.dummy(s, o, p);
        }
        
        public System.Threading.Tasks.Task dummyAsync(ScrapWeb.Webservices.AMQSolicitudMessage s, ScrapWeb.Webservices.AMQOfertaMessage o, ScrapWeb.Webservices.AMQPedidoMessage p) {
            return base.Channel.dummyAsync(s, o, p);
        }
    }
}
